In [1]:
import numpy as np

# Scalars

In [2]:
a = np.array(5)

In [12]:
x = a + 3
x, type(x)

(8, numpy.int64)

# Vectors

In [16]:
v = np.array([1,2,3])
v.shape

(3,)

# Matrices

In [18]:
m = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [20]:
m.shape

(3, 3)

In [23]:
m[0][0]

1

# Tensor

In [26]:
t = np.array([[[[1],[2]],[[3],[4]],[[5],[6]]],[[[7],[8]],\
    [[9],[10]],[[11],[12]]],[[[13],[14]],[[15],[16]],[[17],[17]]]])

In [28]:
t.shape

(3, 3, 2, 1)

# Changing Shapes

In [33]:
v = np.array([1,2,3,4])
v.shape

(4,)

In [ ]:
#### Reshape

In [35]:
a = v.reshape(4, 1)
a, a.shape

(array([[1],
        [2],
        [3],
        [4]]), (4, 1))

In [40]:
a = v.reshape(1, 4)
a, "Shape", a.shape

(array([[1, 2, 3, 4]]), 'Shape', (1, 4))

In [42]:
x = v[None, :]
x

array([[1, 2, 3, 4]])

In [46]:
x = v[:, None]
x

array([[1],
       [2],
       [3],
       [4]])

# Element wise operations

# Pythonic way

In [53]:
values = [1,2,3,4,5]
for i in range(len(values)):
    values[i] += 5

In [55]:
values

[6, 7, 8, 9, 10]

# Numpy way

In [58]:
x = np.array([1, 2, 3, 4])
y = x + 5
y

array([6, 7, 8, 9])

In [61]:
a = np.array([[1,3],[5,7]])
a.shape

(2, 2)

In [63]:
b = np.array([[2,4],[6,8]])
b.shape

(2, 2)

In [64]:
a + b

array([[ 3,  7],
       [11, 15]])

In [65]:
c = np.array([[2,3,6],[4,5,9],[1,8,7]])
c.shape

(3, 3)

In [66]:
a + c

ValueError: operands could not be broadcast together with shapes (2,2) (3,3) 

# NumPy Matrix Multiplication

In [88]:
m = np.array([[1,2,3],[4,5,6]])
m

array([[1, 2, 3],
       [4, 5, 6]])

In [89]:
n = m * 0.25
n

array([[0.25, 0.5 , 0.75],
       [1.  , 1.25, 1.5 ]])

In [93]:
np.multiply(m, 0.25)

array([[0.25, 0.5 , 0.75],
       [1.  , 1.25, 1.5 ]])

# Matrix Product

In [95]:
a = np.array([[1,2,3,4],[5,6,7,8]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [96]:
b = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [97]:
a.shape, b.shape

((2, 4), (4, 3))

In [99]:
c = np.matmul(a, b)
c

array([[ 70,  80,  90],
       [158, 184, 210]])

# Transpose

In [100]:
m = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
m

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [102]:
m.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [106]:
m.transpose()

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [107]:
!jt -t chesterish