In [1]:
import numpy as np


def sigmoid(x):
    """
    Calculate sigmoid
    """
    return 1 / (1 + np.exp(-x))

In [2]:
x = np.array([0.5, 0.1, -0.2])
target = 0.6
learnrate = 0.5

In [3]:
weights_input_hidden = np.array([[0.5, -0.6],
                                 [0.1, -0.2],
                                 [0.1, 0.7]])

weights_hidden_output = np.array([0.1, -0.3])

In [5]:
## Forward pass
hidden_layer_input = np.dot(x, weights_input_hidden)
hidden_layer_output = sigmoid(hidden_layer_input)
hidden_layer_output

array([0.55971365, 0.38698582])

In [6]:
output_layer_in = np.dot(hidden_layer_output, weights_hidden_output)
output = sigmoid(output_layer_in)
output

0.48497343084992534

In [8]:
## Backwards pass
error = target - output
error

0.11502656915007464

In [9]:
output_error_term = error * output * (1 - output)
output_error_term

0.028730669543515018

In [11]:
hidden_error_term = np.dot(output_error_term, weights_hidden_output) * hidden_layer_output * (1 - hidden_layer_output)
hidden_error_term

array([ 0.00070802, -0.00204471])

In [12]:
delta_w_h_o = learnrate * output_error_term * hidden_layer_output

In [14]:
delta_w_i_h = learnrate * hidden_error_term * x[:, None]

In [16]:
x[:, None]

array([[ 0.5],
       [ 0.1],
       [-0.2]])