In [1]:
# Use the numpy library
import numpy as np

In [96]:
def prepare_inputs(inputs):
    input_array = np.array([inputs])
    
    inputs_minus_min = input_array - input_array.min()
    
    inputs_div_max = inputs_minus_min / inputs_minus_min.max()
    
    return input_array, inputs_minus_min, inputs_div_max

In [85]:
def multiply_inputs(m1, m2):
    
    r1, c1 = m1.shape
    r2, c2 = m2.shape
    
    if c1 != r2 and r1 != c2:
        return False
    else:
        if c1 == r2:
            return np.matmul(m1, m2)
        else:
            return np.matmul(m2, m1)

In [66]:
m1 = np.array([[1, 4], [3, 5], [4, 5]])
m2 = np.array([[5, 6, 3], [3, 3,  9], [ 7, 8, 9]])
m2.shape, m1.shape

((3, 3), (3, 2))

In [86]:
multiply_inputs(m1, m2)

2
3


array([[ 35,  65],
       [ 48,  72],
       [ 67, 113]])

In [59]:
def find_mean(values):
    return np.mean(values)

In [97]:
input_array, inputs_minus_min, inputs_div_max = prepare_inputs([-1,2,7])
print("Input as Array: {}".format(input_array))
print("Input minus min: {}".format(inputs_minus_min))
print("Input  Array: {}".format(inputs_div_max))

print("Multiply 1:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1],[2],[3],[4]]))))
print("Multiply 2:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1],[2],[3]]))))
print("Multiply 3:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1,2]]))))

print("Mean == {}".format(find_mean([1,3,4])))

Input as Array: [[-1  2  7]]
Input minus min: [[0 3 8]]
Input  Array: [[0.    0.375 1.   ]]
3
4
Multiply 1:
False
3
3
Multiply 2:
[[14]
 [32]]
3
1
Multiply 3:
[[ 9 12 15]]
Mean == 2.6666666666666665
