In [1]:
import torch
import numpy as np
import torch.nn as nn

# Create a dummy input 

In [2]:
arr = np.array([[[1, 2, 3, 2], [3, 4, 5, 2], [6, 7, 8, 2], [8, 9, 10, 2]]])
arr

array([[[ 1,  2,  3,  2],
        [ 3,  4,  5,  2],
        [ 6,  7,  8,  2],
        [ 8,  9, 10,  2]]])

In [3]:
data = torch.Tensor(arr)

# add another axis (like: batch size)

In [4]:
data = data.unsqueeze(0)

In [5]:
data.shape

torch.Size([1, 1, 4, 4])

In [6]:
data

tensor([[[[ 1.,  2.,  3.,  2.],
          [ 3.,  4.,  5.,  2.],
          [ 6.,  7.,  8.,  2.],
          [ 8.,  9., 10.,  2.]]]])

# Create CNN layers

In [40]:
cnn = nn.Conv2d(1, 2, kernel_size=2, stride=2, padding=1)
output = cnn(data)
output

tensor([[[[ 0.4528,  0.4139,  0.3183],
          [-0.5846, -0.6456,  0.8344],
          [-2.7704, -1.2457,  0.9371]],

         [[-0.2689,  0.0818,  0.8346],
          [-2.0722,  0.6829,  1.1539],
          [-1.4806, -0.4097,  0.3013]]]], grad_fn=<ThnnConv2DBackward>)

In [41]:
output.shape

torch.Size([1, 2, 3, 3])

# Add batch normalization

In [42]:
batch = nn.BatchNorm2d(2)

In [43]:
out1 = batch(output)
out1

tensor([[[[ 0.6269,  0.5924,  0.5077],
          [-0.2927, -0.3468,  0.9651],
          [-2.2301, -0.8787,  1.0561]],

         [[-0.1369,  0.2106,  0.9567],
          [-1.9239,  0.8064,  1.2731],
          [-1.3377, -0.2764,  0.4281]]]], grad_fn=<NativeBatchNormBackward>)

# Add activation function

In [44]:
relu = nn.ReLU()

In [45]:
out2 = relu(out1)
out2

tensor([[[[0.6269, 0.5924, 0.5077],
          [0.0000, 0.0000, 0.9651],
          [0.0000, 0.0000, 1.0561]],

         [[0.0000, 0.2106, 0.9567],
          [0.0000, 0.8064, 1.2731],
          [0.0000, 0.0000, 0.4281]]]], grad_fn=<ReluBackward0>)

# Add pooling

In [46]:
pool = torch.nn.MaxPool2d(2, 2)

In [47]:
out2 = pool(out2)
out2

tensor([[[[0.6269]],

         [[0.8064]]]], grad_fn=<MaxPool2DWithIndicesBackward>)

In [48]:
out2.shape

torch.Size([1, 2, 1, 1])