In [1]:
import numpy as np

final_output = np.array([0.31030254])
hidden_output = np.array([0.37118935, 0.4505258])
x = np.array([ 0.5,-0.2,0.1])
y = np.array([0.4])
weights_hidden_to_output = np.array([[-0.21408145], [0.74831647]])

In [2]:
error = y - final_output
error

array([0.08969746])

In [3]:
output_error_term = error * final_output * (1 - final_output)
output_error_term

array([0.01919659])

# Calculate del w for hidden to output

In [4]:
del_w_hidden_output = output_error_term * hidden_output
del_w_hidden_output

array([0.00712557, 0.00864856])

# Now input to hidden

What is the problem in this cell?


How can I fix this?

In [5]:
hidden_error = np.dot(output_error_term, weights_hidden_to_output)

ValueError: shapes (1,) and (2,1) not aligned: 1 (dim 0) != 2 (dim 0)

In [ ]:
hidden_error_term = hidden_error * hidden_output * (1 - hidden_output)
hidden_error_term

In [ ]:
del_w_input_hidden = hidden_error_term * x[:, None]
del_w_hidden_output